name: Atualizar Licitações

on:
  schedule:
    - cron: '0 2 * * 6' # Toda sexta-feira às 02:00 UTC 2- terça 3-quarta 4-quinta 5-sexta 6-sábado 7-domingo
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update script
        run: python Dados/Coleta_dados/coleta_api.py

      - name: Check for changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'noreply.github.com'
          if git diff --quiet; then
            echo "No changes detected, skipping commit."
            exit 0
          fi

      - name: Commit and push changes
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull origin main
          git add Dados/contratos_OFICIAL.json
          git commit -m "Atualização automática: $(date +'%Y-%m-%d %H:%M:%S')"
          git push